version: '3'
services:
  proxy:
    image: nginx:1.21-alpine
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - logs:/var/log/proxy
    ports:
      - 8080:80
    networks:
      - web

  logparser:
    image: logparser:0.1
    container_name: logparser
    volumes:
      - logs:/var/log/logparser:ro

  web:
    image: ratetest-web:0.1
    container_name: web
    expose:
      - "80"
    networks:
      - web

volumes:
  logs:
networks:
  web:
