version: '3'
services:
  proxy:
    image: nginx:1.21-alpine
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - web

  web:
    image: ratetest-web:0.1
    container_name: web
    expose:
      - "80"
    networks:
      - web

networks:
  web:
