AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaImageUri:
    Description: Lambda image
    Type: String

  NameTag:
    Description: Name Tag to add into resources
    Type: String
    Default: "AudioGwReachabilityTest"

  EnvTag:
    Description: Env Tag
    Type: String
    Default: "Canary" 

Resources:
  AudioGwLambda:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Role:
        Fn::GetAtt:
        - AudioGwLambdaRole
        - Arn
      Code:
        ImageUri: !Ref 'LambdaImageUri'
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 600
      Environment:
        Variables:
          MAX_REACHABILITY_ANALYSIS: 10  
      Tags:
        - Key: Name
          Value: !Ref NameTag
        - Key: Env
          Value: !Ref EnvTag 
  AudioGwLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: Lambda 
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: ResourceGroupTaggingPermissions
            Effect: Allow
            Action:
            - tag:GetResources
            - tag:GetTagKeys
            - tag:GetTagValues          
            Resource: '*'
          - Sid: ReachabilityAnalysisPermissions
            Effect: Allow
            Action:
            - ec2:GetTransitGatewayRouteTablePropagations
            - ec2:DescribeTransitGatewayPeeringAttachments
            - ec2:SearchTransitGatewayRoutes
            - ec2:DescribeTransitGatewayRouteTables
            - ec2:DescribeTransitGatewayVpcAttachments
            - ec2:DescribeTransitGatewayAttachments
            - ec2:DescribeTransitGateways
            - ec2:GetManagedPrefixListEntries
            - ec2:DescribeManagedPrefixLists
            - ec2:DescribeAvailabilityZones
            - ec2:DescribeCustomerGateways
            - ec2:DescribeInstances
            - ec2:DescribeInternetGateways
            - ec2:DescribeNatGateways
            - ec2:DescribeNetworkAcls
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribePrefixLists
            - ec2:DescribeRegions
            - ec2:DescribeRouteTables
            - ec2:DescribeSecurityGroups
            - ec2:DescribeSubnets
            - ec2:DescribeVpcEndpoints
            - ec2:DescribeVpcPeeringConnections
            - ec2:DescribeVpcs
            - ec2:DescribeVpnConnections
            - ec2:DescribeVpnGateways
            - ec2:DescribeVpcEndpointServiceConfigurations
            - elasticloadbalancing:DescribeListeners
            - elasticloadbalancing:DescribeLoadBalancers
            - elasticloadbalancing:DescribeLoadBalancerAttributes
            - elasticloadbalancing:DescribeRules
            - elasticloadbalancing:DescribeTags
            - elasticloadbalancing:DescribeTargetGroups
            - elasticloadbalancing:DescribeTargetHealth
            - tiros:CreateQuery
            - tiros:GetQueryAnswer
            - tiros:GetQueryExplanation
            - ec2:CreateTags
            - ec2:DeleteTags
            - ec2:StartNetworkInsightsAnalysis
            - ec2:DescribeNetworkInsightsAnalyses
            - ec2:DescribeNetworkInsightsPath
            Resource: "*"
      Tags:
        - Key: Name
          Value: !Ref NameTag
        - Key: Env
          Value: !Ref EnvTag

Outputs:
  ReachabilityLambdaArn:
    Description: "AudioGw Reachability Lambda Function ARN"
    Value: !GetAtt AudioGwLambda.Arn
