version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: proxy-srv
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9090:80
    networks:
      - proxy-net
      - web-net

  web:
    image: loadtest-web:latest
    container_name: web-srv
    expose:
      - "8080"
    networks:
      - web-net

networks:
  proxy-net:
  web-net:
